<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class MovementRankingTest extends TestCase
{
    use RefreshDatabase;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->seed();
    }

    public function test_should_be_able_to_get_movement_raking_without_sending_any_movementName()
    {
        $response = $this->getJson(route('getMovementRanking'));
        $response->assertStatus(200);
        $response->assertJsonStructure([[
            '*' => [
                'movement_name',
                'user_name',
                'personal_record',
                'record_date',
                'ranking_position'
            ]
        ]]);
        $this->assertEquals('Deadlift', $response->json()[0][0]['movement_name']);
    }


    public function test_should_only_movement_ranking_deadlift_sending_movementName_equals_deadlift()
    {
        $response = $this->getJson('/api/getMovementRanking?movementName=Deadlift');

        $response->assertStatus(200);
        $response->assertJsonStructure([[
            '*' => [
                'movement_name',
                'user_name',
                'personal_record',
                'record_date',
                'ranking_position'
            ]
        ]]);

        $this->assertEquals('Deadlift', $response->json()[0][0]['movement_name']);
    }
}
